# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 794d471be5f0d8eeb957f64d7a59c036531cf01a41942256996a9713c37361e9f111aabd39382ed0a68717ac4b11257bf2a6c27adf10cdab2ee42faa171e7c04

test:
  secret_key_base: a1f0fb9a92110b74b0836bf6f42be26e42f5bf1536e96e55fc071217a5dfc227351d5bab2e473a81c052283caa9886472361b04a74fe5955f28470c5947da586

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
